### ISSUE TITLE
crash and inconsistent results using port range

### ISSUE THREAD

**Issue by Peperud** [mkautzmann/portquiz#5]
1. Cannot scan the whole range 1-65535. No messages on the console, just exists after awhile.
2. Testing with a port range 1-100 gives me say port 21 and 80 open, but testing with range 1-20000 does not.

How small of a range it can work reliably with?

**Comment by mkautzmann** [comment]
Yes, I managed to reproduce the problem. Working on a fix that should be up soon.

**Comment by mkautzmann** [comment]
The fix is up at NPM, please update your package to version `1.2.3`. Thanks for the heads up @Peperud!
